namespaces:
  controlled:
  - category
  - city
  - language
  - nsfw
  - priority
  - source
  - status
  - subtype
  - cuisine
  - kind
common:
  status:
  - planned
  - in-progress
  - done
  priority:
  - high
  - medium
  - low
  language:
  - ru
  - en
per_type:
  рецепт:
    cuisine:
    - italian
    - greek
    - french
    - asian
    - american
    - mexican
    - japanese
    - chinese
    - indian
    kind:
    - appetizer
    - main
    - dessert
    - soup
    - salad
  место:
    category:
    - культура
    - еда
    - природа
  вишлист:
    priority:
    - high
    - low
    - medium
    category:
    - техника
    - одежда
  учебник:
    status:
    - done
    - in-progress
    - planned
  курс:
    status:
    - done
    - in-progress
    - planned
  мем:
    subtype:
    - meme
    - screenshot
    nsfw:
    - nsfw
  цитата:
    nsfw:
    - 'false'
    - 'true'
  фильм:
    status:
    - done
    - in-progress
    - planned
  книга:
    status:
    - done
    - in-progress
    - planned
  песня:
    status:
    - done
    - in-progress
    - planned
    source:
    - reels
    - tiktok
    - youtube
    - другое
  видео:
    status:
    - done
    - in-progress
    - planned
    source:
    - reels
    - tiktok
    - youtube
    - другое

synonyms:
  cuisine:
    итальянская: italian
    italyanskaya: italian
    греческая: greek
    grecheskaya: greek
    французская: french
    francuzskaya: french
    азиатская: asian
    aziatskaya: asian
    американская: american
    amerikanskaya: american
    мексиканская: mexican
    meksikanskaya: mexican
    японская: japanese
    yaponskaya: japanese
    китайская: chinese
    kitayskaya: chinese
    индийская: indian
    indiyskaya: indian
  kind:
    закуска: appetizer
    zakuska: appetizer
    основное: main
    main: main
    десерт: dessert
    desert: dessert
    суп: soup
    salad: salad
    салат: salad
